code --install-extension adpyke.codesnap
code --install-extension amazonwebservices.aws-toolkit-vscode
code --install-extension anthropic.claude-code
code --install-extension cardinal90.multi-cursor-case-preserve
code --install-extension carlos18mz.cyberpunk-2077-rebuild
code --install-extension codestream.codestream
code --install-extension docker.docker
code --install-extension eamodio.gitlens
code --install-extension fwcd.kotlin
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension github.vscode-pull-request-github
code --install-extension hashicorp.terraform
code --install-extension hediet.debug-visualizer
code --install-extension mathiasfrohlich.kotlin
code --install-extension mechatroner.rainbow-csv
code --install-extension mhutchie.git-graph
code --install-extension ms-azuretools.vscode-azureresourcegroups
code --install-extension ms-azuretools.vscode-containers
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-dotnettools.vscode-dotnet-runtime
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.debugpy
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-python.vscode-python-envs
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension ms-vscode.live-server
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.remote-server
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-windows-ai-studio.windows-ai-studio
code --install-extension phplasma.csv-to-table
code --install-extension pkief.material-icon-theme
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.liveserver
code --install-extension teamsdevapp.vscode-ai-foundry
code --install-extension usernamehw.errorlens
code --install-extension visualstudioexptteam.intellicode-api-usage-examples
code --install-extension visualstudioexptteam.vscodeintellicode